# SITE
url: 'https://AV-CompSci-Mage.github.io/aws-battleship/'
baseurl: ''
permalink: /:title/

title: 'AWS Battleship Project'
description: 'A website documenting our LAB 6 project.'

# build
highlighter: rouge
exclude: ['LICENSE', 'README.md']

# theme
theme: jekyll-theme-minimal
featured-height: 200 # featured image height; options: intiger, default: false (300px)

# pixelate.js - class="pixelate", pixelateAll overides all settings
pixelate-featured: false # pixelate all header images; options: true, false, default: off false (off)
pixelate-all: false # pixelate all images; options: true, false, default: false (off)
